### PR TITLE
Cache config for file URI.

### PR DESCRIPTION
**Pull request by lygstate**
### This changes [[visible behavior/performance/documentation/etc.]]

The following changes are proposed:

- 
- 
-

### CODE REVIEW

**Comment by lygstate** [comment]
@vector-of-bool Can you share your idea about how to deal with the condition when config can not found for the specific file.

**Comment by vector-of-bool** [comment]
@lygstate sorry for the delay.

I had an earlier rendition of a "best guess" on finding the compilation information from `compile_commands.json`. [Here is the important function](https://github.com/vector-of-bool/vscode-cmake-tools/blob/1.0.0/src/compdb.ts#L94).

With that function I could "stem" the file path such that the headers and sources ended up with the same "stem" key.

My new idea involves generating a secondary map of configuration information based on this stem key. If lookup in the primary map fails, it will fall back to this "best guess" map. Since header files will map to the same stem as the corresponding source file, it is very likely that the "best guess" will be correct (if the user has a source file corresponding to the header.) An appropriate diagnostic can be shown recommending that the user add the header file to the source list.

If the secondary map has no configuration for a stemmed file path, then there is no way to reliably determine the configuration information.

**Comment by lygstate** [comment]
@vector-of-bool ping for fixes

**Comment by lygstate** [comment]
@bobbrow That's mainly comes from .inc file and .h files, you propose a good idea, can you suggest a configuration sample? We may create a link in warning notification for automatically create such a configuration file, YAML or JSON

**Comment by bobbrow** [comment]
I'm going to close this PR and create a new feature request for the behavior described. We can continue the discussion there if necessary.

Issue: #1479

**Pull request closed without merging**
