### PR TITLE
correct_inheritence_of_vendor_when_expanding

### PR DESCRIPTION
**Pull request by AdamBartosCodasip**
The following changes are proposed:

- Fix `vendor` inheritance in presets. Without this change, `vendor` fields are inherited only when the child vendor is undefined.

### CODE REVIEW

**Comment by gcampbell-msft** [comment]
@AdamBartosCodasip We recently made some refactors and changes to the expanding of presets, could you re-assess this PR to make sure, 1) this is still necessary, and 2) whether this still does what you expect?

**Review by gcampbell-msft — CHANGES_REQUESTED** [review]
See other comment.

**Comment by kodsingalur** [comment]
This is not needed anymore. Thanks.

**Comment by AdamBartosCodasip** [comment]
This is not needed anymore. Thanks.

**Pull request closed without merging**
