### PR TITLE
Detection of Clang for MSVC (GNU CLI) kits

### PR DESCRIPTION
**Pull request by Zingam**
## This change addresses item #823

The following changes are proposed:

- Scanning for clang.exe with GNU-like CLI
- Full compiler path will be displayed in the description of kits for Clang in QuickPick
- A suffix (GNU CLI) will be displayed in the kit name if a GNU CLI compatible Clang kits

## The purpose of this change

Creation of kits for Clang for MSVC ABI with GNU-like CLI

## Other Notes/Information

- CMake 3.15+ supports Clang for MSVC ABI with GNU-like CLI
- This PR builds upon #930

### CODE REVIEW

**Review by andreeis — APPROVED** [review]

**Comment by xoviat** [comment]
Is there a way to force the clang-cl CLI?

**Comment by andreeis** [comment]
What do you mean? Currently we also detect clang MSVC CLI, MSVC being cl. Do you not have the MSVC clang kits detected on your system?

**Comment by xoviat** [comment]
> Do you not have the MSVC clang kits detected on your system?

Correct. Should I open a new issue?

**Comment by Zingam** [comment]
> > Do you not have the MSVC clang kits detected on your system?
> 
> Correct. Should I open a new issue?

If you have an issue, you should open a bug report. And also please give as much information as possible.

**Pull request merged**
