### PR TITLE
CI for Windows

### PR DESCRIPTION
**Pull request by bobbrow**
This is an experiment to see where we are for CI on Windows.  It hasn't been available since we started the project and I expect that many tests will fail as they will need to be snapped to a specific set of Kits.  This should allow us to learn what the Kits look like on the Windows VM.

### CODE REVIEW

**Comment by lygstate** [comment]
Maybe it's better to getting these tests can running locally

**Review by andreeis — APPROVED** [review]

**Comment by lygstate** [comment]
ask for this

**Comment by lygstate** [comment]
closed?

**Comment by bobbrow** [comment]
It's not ready for review.  This should have been marked as "draft" because my goal was just to see where CI was for this.  I'm doing some investigation of test bugs on my local machine and slowly making progress.  I will reopen this when it's ready to review.

**Pull request closed without merging**
