### PR TITLE
Add a control statement to the 'quote' function in shlex.ts to return the string without quotes

### PR DESCRIPTION
**Pull request by nasinlock**
## This change addresses item #2955 

The following changes are proposed:

- Add a control statement to the 'quote' function in shlex.ts to return the string without quotes if there are no white space characters in the string.

## Other Notes/Information

N/A

### CODE REVIEW

**Comment by elahehrashedi** [comment]
@nasinlock 
Would you please change the CHANGELOG as well? similar to this PR? the change will go into 1.13.41
Also, would you please merge this PR to release/1.13 branch instead of the main?

**Comment by nasinlock** [comment]
> 

I've updated the Changelog

**Comment by elahehrashedi** [comment]
@nasinlock Also, would you please merge this PR to "release/1.13" branch instead of the main?

**Comment by nasinlock** [comment]
> @nasinlock Also, would you please merge this PR to "release/1.13" branch instead of the main?

Sure. I'll have to rebase my branch to release/1.13 to avoid pulling in extra changes

**Comment by bobbrow** [comment]
this fix is small enough that it could be done in main and cherry picked to release/1.13 (if that's easier)

**Review by bobbrow — CHANGES_REQUESTED** [review]
This is pulling all the 1.14 commits into 1.13.  It shouldn't do that.

**Pull request closed without merging**
