### PR TITLE
Fix paths of target sources outside the workspace

### PR DESCRIPTION
**Pull request by sleiner**
### This changes visible behavior

Target sources from outside the VS Code workspace folder are now represented with their correct paths.
Furthermore, if the user clicks on them, instead of an error message, the correct file opens 😃

## Other Notes/Information

This is not thoroughly tested yet. But everything looks fine for with VS Code 1.55.2 on macOS and a very simple example project.

### CODE REVIEW

**Comment by bobbrow** [comment]
Interesting.  I actually stumbled on this old PR that was closed without review/merge and it appears to address the same issue.  https://github.com/microsoft/vscode-cmake-tools/pull/1635/files

**Comment by sleiner** [comment]
Oh yeah, I see. As far as I see, it does exactly the same thing (although in a slightly different way) 👍 
How would you like to proceed?

**Comment by sleiner** [comment]
I just tested this with a more complex project. Turns out: My approach fails when the target's source root is not the same as the workspace root. (In context of the `convertToExtCodeModelFileGroup` function: `targetObject.paths.source != "."` still produces incorrect paths with my patch. On the other hand, #1635 handles it correctly.
So I propose closing this PR and instead applying the patches from #1635. Is that alright with you?

**Comment by bobbrow** [comment]
That user closed the PR and we didn't hear back, so if you could update your PR with the changes needed, we'll approve it and get it in.

**Comment by sleiner** [comment]
Alright, I'm ready 👍 Could you allow CI execution?

**Comment by bobbrow** [comment]
@andreeis we forgot to mark the milestone on this one.  The code change is pretty small - this is mostly adding tests.  Should we take it in 1.7.2?

**Comment by andreeis** [comment]
I think we can, of course, I am looking at it now.

**Review by andreeis — APPROVED** [review]

**Pull request merged**
