### PR TITLE
Fix GitHub 1401, diagnostics relative to workspace folder

### PR DESCRIPTION
**Pull request by fargies**
### This changes how relative filepath in diagnostics are resolved

The following changes are proposed:
 - relative diagnostics files are searched in build_dir and src_dir, first existing file is returned
 - defaults to old behavior : `path.resolve(build_dir, file)`
 - `resolveDiagnostics` has been made async to not slow down IDE when testing files

## The purpose of this change

Depending on tools, compiler and CMake invocation, diagnostics paths may be relative, but either to source directory or build directory.

This is a try and guess approach, with a preference for old behavior (returning `build_dir/file`).

### CODE REVIEW

**Comment by fargies** [comment]
> @microsoft-github-policy-service agree company="CERN"

**Review by gcampbell-msft — CHANGES_REQUESTED** [review]
These changes look reasonable to me, but please make a CHANGELOG update and feel free to give yourself credit using examples already present in the changelog. Thanks!

**Comment by fargies** [comment]
> These changes look reasonable to me, but please make a CHANGELOG update and feel free to give yourself credit using examples already present in the changelog. Thanks!

Sure, there you are.

Thanks

**Review by gcampbell-msft — APPROVED** [review]

**Review by gcampbell-msft — CHANGES_REQUESTED** [review]
@fargies It looks like the test that you created is failing on Windows, could you investigate?

**Review by gcampbell-msft — APPROVED** [review]

**Pull request merged**
