### PR TITLE
Configure precondition handler to return boolean to signal a successful recovery case

### PR DESCRIPTION
**Pull request by andreeis**
Fix for bug https://github.com/microsoft/vscode-cmake-tools/issues/3554.

This modifies our preConditionHandler to ensure that we properly update our state such that the next time someone tries to configure or build, it is able to successfully configure/build. 

There should be more changes in the future to allow this to happen on the original invocation, but it will more of an enhancement and more complex. For this fix, it will simply be a bug fix that allows you to manually try again.

### CODE REVIEW

**Comment by andreeis** [comment]
Latest commit was done into this branch by mistake, it was meant for another bug.

**Comment by gcampbell-msft** [comment]
@andreeis This PR looks good, but do we need a CHANGELOG.md update?

**Review by snehara99 — APPROVED** [review]

**Review by gcampbell-msft — DISMISSED** [review]

**Review by gcampbell-msft — DISMISSED** [review]

**Comment by gcampbell-msft** [comment]
Just changelog update, no need to rebuild.

**Review by moyo1997 — APPROVED** [review]

**Comment by gcampbell-msft** [comment]
Already approved, merging.

**Review by moyo1997 — APPROVED** [review]

**Pull request merged**
