### PR TITLE
Add vendor hostOs targetOs targetArch versionMajor versionMinor attributes for kit.

### LINKED ISSUE #462: Question? How to use kits in     "cmake.buildDirectory"
I want to use something like this to building for different compiler & tartget : "${workspaceRoot}/build/${buildType}-$(buildKit}",

such as Visual Studio 2017 amd 64& Visual Studio 2015 x86 & LLVM Cross for Linux and so on.

### PR DESCRIPTION
**Pull request by lygstate**
Add vendor hostOs targetOs targetArch versionMajor versionMinor attributes for kit.
Fixes #462

### CODE REVIEW

**Comment by bobbrow** [comment]
Thank you for your contribution.  One quick question.  Is it possible to query these attributes at the point where the kit is selected instead of modifying the definition of a Kit?  Changing the Kit definition on disk is disruptive for people and I haven't reviewed this PR extensively enough to determine whether it is actually required.

**Comment by lygstate** [comment]
I am not sure if that possible, cause it's need the version info of the compiler, and that was detected at the scan procedure

**Comment by lygstate** [comment]
Where does the travis result gone.

**Comment by bobbrow** [comment]
The detection just invokes the compiler with `-v` and reads the stderr. I think that could be done when the kit is selected.

**Comment by lygstate** [comment]
> The detection just invokes the compiler with `-v` and reads the stderr. I think that could be done when the kit is selected.

OK, I'll try it:)

**Comment by lygstate** [comment]
@bobbrow done, wish you have time to do a review. I add a function getKitExpand to be called in _setKit

**Comment by lygstate** [comment]
CI not triggered again.

**Comment by lygstate** [comment]
> The detection just invokes the compiler with `-v` and reads the stderr. I think that could be done when the kit is selected.

I've modify the patch with you suggestion, need feedback, thanks

**Comment by lygstate** [comment]
@bobbrow  ping for merge

**Comment by andreeis** [comment]
We apologize for taking so long to finalize a review of this change. We are wrapping up another project. Thank you for your patience while we catch up with the PRs and high priority bugs.

**Review by andreeis — APPROVED** [review]

**Pull request merged**
