### PR TITLE
Discover all Visual Studio Installs.

### PR DESCRIPTION
**Pull request by pokowaka**
It is possible to have multiple versions of Visual Studio. For example
Professional and Enterprise. Previously only one version could be
registered, potentially causing problems.

Closes: #611
Test: Scanning of kits succeed, with reasonable (but longer) display name.

### This changes visible behavior

The following changes are proposed:

Now shows the complete name of Visual Studio in discovered kits

## The purpose of this change

Fix a bug when there are multiple installations of visual studio, but making only one available.

### CODE REVIEW

**Comment by lygstate** [comment]
Gocha have a try:)

**Comment by lygstate** [comment]
@pokowaka I am confused why only one version could be registered。
I prefer
      inst.instanceId = `VisualStudio.${majorVersion}.0.Commnity`;
      inst.instanceId = `VisualStudio.${majorVersion}.0.Professional`;
and so on.

**Comment by pokowaka** [comment]
The reason only one version gets registered is due to line 379. Only the first instance id gets registered.

I don't think it is worth it to have a display name translator that saves 5 chars for the following reasons.

- The code will be more complicated, as we will have to determine which type is installed (Enterprise/Community/Prof/etc). 
- The proposed scheme will cause complications if Microsoft drops or adds a new "release type". For example community editions where named express at a certain point.
- Not clear what the added value of .0. in the string is.

**Comment by lygstate** [comment]
@pokowaka For consistence with older version of visual Studio.

**Comment by blakehurd** [comment]
Hello, per the wording of this issue, would this potentially help with CMake Tools not discovering msvc_x64 / x64 kit when it scans? It picks up amd64, x86, amd64_arm, etc., but does not clearly pick up x64 separately even though the requisite exe/etc. are located right next to x86 per the Visual Studio Installer. Ended up needing to define a kit anyway to specify a vcpkg toolchain, but would've helped to have this at the start.

**Comment by pokowaka** [comment]
@vector-of-bool  how can we move forward addressing this issue?

**Comment by lygstate** [comment]
@vector-of-bool How about give me admin permission to merge request and submit pathches?

**Comment by bobbrow** [comment]
I'm happy to merge this, but is it still an issue?  I see both "Build Tools" and "Enterprise" for VS 2017 on my machine in the latest version of CMake Tools.

image

**Comment by pokowaka** [comment]
> I'm happy to merge this, but is it still an issue? I see both "Build Tools" and "Enterprise" for VS 2017 on my machine in the latest version of CMake Tools.
> 
> image

The problem only arises when the same major version is the same. The case would be installing 2019 Enterprise next to 2019 Build Tools. Only one of the two will show up.

**Comment by bobbrow** [comment]
Is it not a problem with Preview builds then?  I have Build Tools 2017 and Enterprise 2017 (Preview).

**Comment by bobbrow** [comment]
I've been testing this on my PC and there are still some issues.
* My VS 2019 and 2019 Preview builds are not both showing up because they have the same display name (`isPrerelease` differentiates these)
* The description string for choosing a kit ("using compilers from ...") is a bit too long with this change. It would be more informational if the major.minor version appeared here since the displayName is already visible.

I'm trying to think of a way to have all this information available with the current Kits schema, but this may just require a forced full rescan of kits to get right.

**Comment by bobbrow** [comment]
I have a new PR at #719 that should address all of these pieces.

**Comment by pokowaka** [comment]
Newer change address all concerns. PR no longer relevant.

**Pull request closed without merging**
