### PR TITLE
Assign names to status bar items

### PR DESCRIPTION
**Pull request by chausner**
## This change addresses item #1933

This assigns a name to each button on the status bar which allows users to individually show/hide buttons. Before this change, users can only show/hide all buttons at once.

Users have reported in https://github.com/microsoft/vscode-cmake-tools/issues/1945 that the status bar buttons take up a lot of space. Allowing users to hide individual buttons that they might not need (e.g. tests) could help.

In order to use the newer `createStatusBarItem` overload, I had to update `@types/vscode` to a newer version. I picked `1.63.0` which matches the minimum VS Code version specified in `package.json`:
```json
"engines": {
    "vscode": "^1.63.0"
  },
```
As part of this update, I had to make some minor changes to the mocking and tests code.

The names assigned to the buttons are shown in the context menu of the status bar:

image

They would need to be localized.

### CODE REVIEW

**Comment by bobbrow** [comment]
We do have settings in the extension that allow you to control the status bar such as how much space they use and which ones appear.  I'm concerned that adding all of these to that list will make it overly noisy.

The setting that controls this is `cmake.statusbar.advanced`.

**Comment by chausner** [comment]
Oh, I did not know about the advanced settings for configuring the status bar. I agree that the many items make the context menu a bit crowded. On the other hand, some users like me might not know about the ability to hide some of the status bar items via the settings, and the context menu provides a more intuitive and consistent way to configure that. So I think there are pros and cons to both approaches, and either way is fine for me.

If you decide to leave it as it is, maybe it still makes sense to merge the update of `@types/vscode` to `1.63.0` so that it matches the minimum engine version.

**Comment by bobbrow** [comment]
There is also issue #1582 which I think we still want to do.  This would move us in the direction of managing project state in the sidebar instead of the status bar.

**Comment by elahehrashedi** [comment]
Thank you for your contribution. Unfortunately, this is not the direction we want to take, and we encourage users to use the settings to control the status bar.

**Pull request closed without merging**
