### PR TITLE
rename ci scripts to match the branch

### PR DESCRIPTION
**Pull request by bobbrow**

### CODE REVIEW

**Comment by elahehrashedi** [comment]
I have been wanting to change `DerYeger/yarn-setup-action@v1.0.1` to `DerYeger/yarn-setup-action@master` in previous PR.

**Comment by bobbrow** [comment]
> I have been wanting to change `DerYeger/yarn-setup-action@v1.0.1` to `DerYeger/yarn-setup-action@master` in previous PR.

It's risky to point to the master branch of an action in case it makes changes that break your CI. I would prefer we stick to a specific version that we know works.

**Comment by elahehrashedi** [comment]
May I ask why not "v3.19.0"?

**Comment by bobbrow** [comment]
> May I ask why not "v3.19.0"?

The other platforms use 3.18.3. It's best to use the same version for all the tests.  I'm hoping parts of the setup could be made common across platforms at some point.

**Review by elahehrashedi — APPROVED** [review]

**Pull request merged**
