### PR TITLE
Add `onSelectedConfigurationChanged` api

### PR DESCRIPTION
**Pull request by OrkunTokdemir**
I added a new event api for the select kit change. It is needed for our extension to detect it. I guess I should also prepare a pull request for https://github.com/microsoft/vscode-cmake-tools-api.

### CODE REVIEW

**Comment by OrkunTokdemir** [comment]
@microsoft-github-policy-service agree

**Comment by OrkunTokdemir** [comment]
@gcampbell-msft Can you please take a look when you're available?

**Comment by gcampbell-msft** [comment]
@OrkunTokdemir We'd be happy to take this change, but we'd like to have the respective change in the vscode-cmake-tool-api if possible. Could you make this change as well? We're happy to help with this if needed!

**Comment by OrkunTokdemir** [comment]
> @OrkunTokdemir We'd be happy to take this change, but we'd like to have the respective change in the vscode-cmake-tool-api if possible. Could you make this change as well? We're happy to help with this if needed!

@gcampbell-msft  Thank you. I created a PR in that repo.
https://github.com/microsoft/vscode-cmake-tools-api/pull/8

**Comment by gcampbell-msft** [comment]
@OrkunTokdemir Could you test with the most recent commit? This should update the package.json dependency from the vscode-cmake-tools npm package, and should be fully functional. Thanks!

**Comment by OrkunTokdemir** [comment]
> @OrkunTokdemir Could you test with the most recent commit? This should update the package.json dependency from the vscode-cmake-tools npm package, and should be fully functional. Thanks!

@gcampbell-msft Thank you for updating the dependencies. I tested some more detailed cases. All of them look fine. Found a little problem and fixed it with  https://github.com/microsoft/vscode-cmake-tools/pull/3671/commits/28ef5b578530092b0fbec00e549b2027de57f49f

LGTM :rocket:

**Pull request merged**
