### PR TITLE
Handle exceptions on testing non-executable 'clang-cl*' files

### PR DESCRIPTION
**Pull request by Zingam**
This fixes: https://github.com/microsoft/vscode-cmake-tools/issues/895

### CODE REVIEW

**Comment by bobbrow** [comment]
Something like this: https://github.com/microsoft/vscode-cmake-tools/commit/4c1c3f5de377370976f63edc878d64af2ffae824

**Comment by Zingam** [comment]
@bobbrow Thanx! I'll look into this deeper later and will also make the necessary changes to the call sites.

**Comment by bobbrow** [comment]
I can just submit my fix if you want.  You shouldn't need to update any call sites.  This will take care of all of them

**Comment by Zingam** [comment]
I think this error message will be confusing and needs to be updated:
`log.debug(localize('bad.clang.binary', 'Bad Clang binary ("-v" returns non-zero): {0}', binPath));`
and we could also log a debug message in  getCMakeExecutableInformation(path: string)

**Comment by Zingam** [comment]
If you think that's not necessary. Then please submit your fix and I'll delete mine.

**Comment by bobbrow** [comment]
I thought the message was ok.  It says that clang-cl.txt is a bad clang binary.

**Comment by bobbrow** [comment]
It's part of the debug log, so it has more details about what went wrong. I'm ok with changing it though. Maybe showing the full command line would be better?

**Comment by Zingam** [comment]
@bobbrow That might be a good idea actually.

**Pull request closed without merging**
